spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tennis_results
    username: ${DB_USER:tennis_user}
    password: ${DB_PASSWORD:tennis_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8082
